version: '3'
services:

  mysql:
    image: mysql:8
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
    networks:
      - service-network

  mongodb:
    image: mongo:5.0
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root


  gateway:
    depends_on:
      - dbservice
      - authservice
    networks:
      - service-network
    build: 
      context: ./hr-gate-way
      dockerfile: Dockerfile
    restart: always
    hostname: gateway
    ports:
      - "3000:3000"
    volumes:
      - ./hr-gate-way:/usr/src/app
    command:
      - yarn
      - start:dev
  dbservice:
    depends_on:
      - mysql
    build: 
      context: ./services/db-service
      dockerfile: Dockerfile
    networks:
      - service-network
    restart: always
    hostname: db-service
    volumes:
      - ./services/db-service:/usr/src/app
    command:
      - yarn
      - start:dev
networks:
  service-network:
    driver: bridge
    
    

      